name: Build user transformer image for DEV deployments
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rudderlabs
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]ut-$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Docker build, tag, test and push images
        run: |
          docker build -t rudderlabs/develop-rudder-transformer:${{ steps.extract_branch.outputs.branch }} -f Dockerfile-ut-func . --build-arg version="${{ steps.extract_branch.outputs.branch }}" --build-arg GIT_COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          docker run rudderlabs/develop-rudder-transformer:${{ steps.extract_branch.outputs.branch }} npm run testDestinations
          docker run rudderlabs/develop-rudder-transformer:${{ steps.extract_branch.outputs.branch }} npm run testVersionedRouter
          docker push rudderlabs/develop-rudder-transformer:${{ steps.extract_branch.outputs.branch }}
